package list

import (
	"github.com/rprtr258/tea/styles"
)

const (
	bullet   = '•'
	ellipsis = "…"
)

// Styles contains style definitions for this list component. By default, these
// values are generated by DefaultStyles.
type Styles struct {
	TitleBar     styles.Style
	Title        styles.Style
	Spinner      styles.Style
	FilterPrompt styles.Style
	FilterCursor styles.Style

	// Default styling for matched characters in a filter. This can be
	// overridden by delegates.
	DefaultFilterCharacterMatch styles.Style

	StatusBar             styles.Style
	StatusEmpty           styles.Style
	StatusBarActiveFilter styles.Style
	StatusBarFilterCount  styles.Style

	NoItems styles.Style

	PaginationStyle styles.Style

	// Styled characters.
	ActivePaginationDot   styles.Style
	InactivePaginationDot styles.Style
	ArabicPagination      styles.Style
	DividerDot            styles.Style
}

var (
	verySubduedColor = styles.FgAdaptiveColor("#DDDADA", "#3C3C3C")
	subduedColor     = styles.FgAdaptiveColor("#9B9B9B", "#5C5C5C")
	// DefaultStyle is a set of default style definitions for list component.
	DefaultStyle = Styles{
		TitleBar: styles.Style{},
		// Padding(0, 0, 1, 2),
		Title: styles.Style{}.
			Background(styles.BgColor("62")).
			Foreground(styles.FgColor("230")),
		// Padding(0, 1),
		Spinner: styles.Style{}.
			Foreground(styles.FgAdaptiveColor("#8E8E8E", "#747373")),
		FilterPrompt: styles.Style{}.
			Foreground(styles.FgAdaptiveColor("#04B575", "#ECFD65")),
		FilterCursor: styles.Style{}.
			Foreground(styles.FgAdaptiveColor("#EE6FF8", "#EE6FF8")),
		DefaultFilterCharacterMatch: styles.Style{}.
			Underline(),
		StatusBar: styles.Style{}.
			Foreground(styles.FgAdaptiveColor("#A49FA5", "#777777")),
		// Padding(0, 0, 1, 2),
		StatusEmpty: styles.Style{}.
			Foreground(subduedColor),
		StatusBarActiveFilter: styles.Style{}.
			Foreground(styles.FgAdaptiveColor("#1a1a1a", "#dddddd")),
		StatusBarFilterCount: styles.Style{}.
			Foreground(verySubduedColor),
		NoItems: styles.Style{}.
			Foreground(styles.FgAdaptiveColor("#909090", "#626262")),
		ArabicPagination: styles.Style{}.
			Foreground(subduedColor),
		PaginationStyle: styles.Style{},
		// PaddingLeft(2), //nolint:gomnd
		ActivePaginationDot: styles.Style{}.
			Foreground(styles.FgAdaptiveColor("#847A85", "#979797")),
		InactivePaginationDot: styles.Style{}.
			Foreground(verySubduedColor),
		DividerDot: styles.Style{}.
			Foreground(verySubduedColor),
	}
)
